# This file is part of Edgehog.
#
# Copyright 2021, 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

import Config

url_host = System.get_env("URL_HOST", "localhost")
url_port = System.get_env("URL_PORT", "4000")
url_scheme = System.get_env("URL_SCHEME", "http")

database = %{
  username: System.get_env("DATABASE_USERNAME", "postgres"),
  password: System.get_env("DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DATABASE_HOSTNAME", "localhost"),
  name: System.get_env("DATABASE_NAME", "edgehog_dev")
}

config :azurex, Azurex.Blob.Config,
  api_url: "http://localhost:10000/devstoreaccount1",
  default_container: "edgehog",
  storage_account_name: "devstoreaccount1",
  storage_account_key: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="

# Configure your database
config :edgehog, Edgehog.Repo,
  username: database.username,
  password: database.password,
  database: database.name,
  hostname: database.hostname,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Mimic production environment variables, default to phoenix defaults.

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :edgehog, EdgehogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {127, 0, 0, 1}` to deny access from other machines.
  http: [
    ip: {0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  url: [
    host: url_host,
    scheme: url_scheme,
    port: url_port
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "uEb3NXr0KodsrjUUUo98VBEExFFAolxlfOW7ZzP/OGgd1R2pDhwMddZXjvUp/3MW",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: "9000"

config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin"

config :goth,
  disabled: true

# Do not include timestamps in development logs
config :logger, :console, format: "[$level] $message $metadata\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :waffle,
  storage: Waffle.Storage.S3,
  bucket: "edgehog",
  asset_host: "http://localhost:9000/edgehog",
  virtual_host: true
