#
# This file is part of Edgehog.
#
# Copyright 2024 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.DevicesCascadingDeleteDeployments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:application_deployments, "application_deployments_device_id_fkey")

    alter table(:application_deployments) do
      modify :device_id,
             references(:devices,
               column: :id,
               name: "application_deployments_device_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER TABLE application_deployments alter CONSTRAINT application_deployments_device_id_fkey NOT DEFERRABLE"
    )
  end

  def down do
    drop constraint(:application_deployments, "application_deployments_device_id_fkey")

    alter table(:application_deployments) do
      modify :device_id,
             references(:devices,
               column: :id,
               name: "application_deployments_device_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
