#
# This file is part of Edgehog.
#
# Copyright 2024 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.RenameImageCredentialsNameLabel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:image_credentials), :name, to: :label

    alter table(:image_credentials) do
      modify :label, :text
    end

    drop_if_exists unique_index(:image_credentials, [:tenant_id, :name],
                     name: "image_credentials_name_index"
                   )

    create unique_index(:image_credentials, [:tenant_id, :label],
             name: "image_credentials_label_index"
           )
  end

  def down do
    drop_if_exists unique_index(:image_credentials, [:tenant_id, :label],
                     name: "image_credentials_label_index"
                   )

    create unique_index(:image_credentials, [:tenant_id, :name],
             name: "image_credentials_name_index"
           )

    alter table(:image_credentials) do
      modify :name, :text
    end

    rename table(:image_credentials), :label, to: :name
  end
end
