#
# This file is part of Edgehog.
#
# Copyright 2024 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.VersionReleaseIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:application_releases, [:tenant_id, :application_id, :version],
                     name: "application_releases_application_version_index"
                   )

    create unique_index(:application_releases, [:tenant_id, :version, :application_id],
             name: "application_releases_application_version_index"
           )

    alter table(:application_deployments) do
      modify :status, :text, null: false, default: "created"
    end
  end

  def down do
    alter table(:application_deployments) do
      modify :status, :text, null: true, default: nil
    end

    drop_if_exists unique_index(:application_releases, [:tenant_id, :version, :application_id],
                     name: "application_releases_application_version_index"
                   )

    create unique_index(:application_releases, [:tenant_id, :application_id, :version],
             name: "application_releases_application_version_index"
           )
  end
end
