#
# This file is part of Edgehog.
#
# Copyright 2024 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.CreateContainerNetwork do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:networks) do
      modify :enable_ipv6, :boolean, default: false
      modify :internal, :boolean, default: false
      modify :check_duplicate, :boolean, default: false
    end

    alter table(:containers) do
      modify :image_id, :uuid, null: false
    end

    create table(:container_networks, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "container_networks_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :container_id,
          references(:containers,
            column: :id,
            name: "container_networks_container_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :network_id,
          references(:networks,
            column: :id,
            name: "container_networks_network_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create index(:container_networks, [:tenant_id])
  end

  def down do
    drop constraint(:container_networks, "container_networks_tenant_id_fkey")

    drop constraint(:container_networks, "container_networks_container_id_fkey")

    drop constraint(:container_networks, "container_networks_network_id_fkey")

    drop_if_exists index(:container_networks, [:tenant_id])

    drop table(:container_networks)

    alter table(:containers) do
      modify :image_id, :uuid, null: true
    end

    alter table(:networks) do
      modify :check_duplicate, :boolean, default: nil
      modify :internal, :boolean, default: nil
      modify :enable_ipv6, :boolean, default: nil
    end
  end
end
