#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.RemoveDeploymentChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:device_groups) do
      remove :deployment_channel_id
    end

    alter table(:deployment_campaign) do
      remove :deployment_channel_id

      add :channel_id,
          references(:channels,
            column: :id,
            with: [tenant_id: :tenant_id],
            match: :full,
            name: "deployment_campaign_channel_id_fkey",
            type: :integer,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false
    end

    create index(:deployment_campaign, [:tenant_id, :channel_id])
  end

  def down do
    drop_if_exists index(:deployment_campaign, [:tenant_id, :channel_id])

    drop constraint(:deployment_campaign, "deployment_campaign_channel_id_fkey")

    alter table(:deployment_campaign) do
      remove :channel_id

      add :deployment_channel_id,
          references(:deployment_channels,
            column: :id,
            name: "deployment_campaign_deployment_channel_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:device_groups) do
      add :deployment_channel_id,
          references(:deployment_channels,
            column: :id,
            name: "device_groups_deployment_channel_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
