#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddVolumeAndNetworkLabels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:volumes) do
      add :label, :text, null: false
    end

    create unique_index(:volumes, [:tenant_id, :label], name: "volumes_label_index")

    alter table(:networks) do
      add :label, :text
    end

    create unique_index(:networks, [:tenant_id, :label], name: "networks_label_index")
  end

  def down do
    drop_if_exists unique_index(:networks, [:tenant_id, :label], name: "networks_label_index")

    alter table(:networks) do
      remove :label
    end

    drop_if_exists unique_index(:volumes, [:tenant_id, :label], name: "volumes_label_index")

    alter table(:volumes) do
      remove :label
    end
  end
end
