#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.UpdateChannelToChannel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:update_channels), to: table(:channels)

    # Note: Ecto.Migration doesn't provide functions for renaming indexes/constraints, so we use execute
    execute "ALTER INDEX update_channels_handle_index RENAME TO channels_handle_index"
    execute "ALTER INDEX update_channels_name_index RENAME TO channels_name_index"
    execute "ALTER INDEX update_channels_id_tenant_id_index RENAME TO channels_id_tenant_id_index"
    execute "ALTER INDEX update_channels_tenant_id_index RENAME TO channels_tenant_id_index"

    execute "ALTER TABLE channels RENAME CONSTRAINT update_channels_tenant_id_fkey TO channels_tenant_id_fkey"

    drop_if_exists index(:update_campaigns, [:tenant_id, :update_channel_id])

    rename table(:update_campaigns), :update_channel_id, to: :channel_id

    execute "ALTER TABLE update_campaigns RENAME CONSTRAINT update_campaigns_update_channel_id_fkey TO update_campaigns_channel_id_fkey"

    create index(:update_campaigns, [:tenant_id, :channel_id])

    rename table(:device_groups), :update_channel_id, to: :channel_id

    execute "ALTER TABLE device_groups RENAME CONSTRAINT device_groups_update_channel_id_fkey TO device_groups_channel_id_fkey"
  end

  def down do
    execute "ALTER TABLE device_groups RENAME CONSTRAINT device_groups_channel_id_fkey TO device_groups_update_channel_id_fkey"

    rename table(:device_groups), :channel_id, to: :update_channel_id

    drop_if_exists index(:update_campaigns, [:tenant_id, :channel_id])

    execute "ALTER TABLE update_campaigns RENAME CONSTRAINT update_campaigns_channel_id_fkey TO update_campaigns_update_channel_id_fkey"

    rename table(:update_campaigns), :channel_id, to: :update_channel_id

    create index(:update_campaigns, [:tenant_id, :update_channel_id])

    execute "ALTER TABLE channels RENAME CONSTRAINT channels_tenant_id_fkey TO update_channels_tenant_id_fkey"

    execute "ALTER INDEX channels_tenant_id_index RENAME TO update_channels_tenant_id_index"
    execute "ALTER INDEX channels_id_tenant_id_index RENAME TO update_channels_id_tenant_id_index"
    execute "ALTER INDEX channels_name_index RENAME TO update_channels_name_index"
    execute "ALTER INDEX channels_handle_index RENAME TO update_channels_handle_index"

    rename table(:channels), to: table(:update_channels)
  end
end
