#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddDeploymentEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deployment_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "deployment_events_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :deployment_id,
          references(:application_deployments,
            column: :id,
            name: "deployment_events_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:deployment_events, [:tenant_id])

    create index(:deployment_events, [:id, :tenant_id], unique: true)

    alter table(:application_deployments) do
      add :timed_out, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:application_deployments) do
      remove :timed_out
    end

    drop constraint(:deployment_events, "deployment_events_tenant_id_fkey")

    drop constraint(:deployment_events, "deployment_events_deployment_id_fkey")

    drop_if_exists index(:deployment_events, [:id, :tenant_id])

    drop_if_exists index(:deployment_events, [:tenant_id])

    drop table(:deployment_events)
  end
end
