defmodule Edgehog.Repo.Migrations.AddQuotasToCreateContainer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:containers) do
      add :cpuPeriod, :bigint, null: false, default: -1
      add :cpuQuota, :bigint, null: false, default: -1
      add :cpuRealTimePeriod, :bigint, null: false, default: -1
      add :cpuRealtimeRuntime, :bigint, null: false, default: -1
      add :memory, :bigint, null: false, default: -1
      add :memoryReservation, :bigint, null: false, default: -1
      add :memorySwap, :bigint, null: false, default: -2
      add :memorySwappiness, :bigint, null: false, default: -1
      add :volumeDriver, :text, null: false, default: ""
      add :storageOpt, {:array, :text}, null: false, default: []
      add :readOnlyRootfs, {:array, :text}, null: false, default: []
      add :tmpfs, {:array, :text}, null: false, default: []
    end

    alter table(:applications) do
      modify :system_model_id, :bigint
    end
  end

  def down do
    alter table(:applications) do
      modify :system_model_id, :integer
    end

    alter table(:containers) do
      remove :tmpfs
      remove :readOnlyRootfs
      remove :storageOpt
      remove :volumeDriver
      remove :memorySwappiness
      remove :memorySwap
      remove :memoryReservation
      remove :memory
      remove :cpuRealtimeRuntime
      remove :cpuRealTimePeriod
      remove :cpuQuota
      remove :cpuPeriod
    end
  end
end
