#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddMappingsToContainers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :path_on_host, :text, null: false
      add :path_in_container, :text, null: false
      add :cgroup_permissions, :text, null: false

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "device_mappings_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :container_id,
          references(:containers,
            column: :id,
            name: "device_mappings_container_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: true
    end

    create index(:device_mappings, [:tenant_id])

    create index(:device_mappings, [:id, :tenant_id], unique: true)
  end

  def down do
    drop constraint(:device_mappings, "device_mappings_tenant_id_fkey")

    drop constraint(:device_mappings, "device_mappings_container_id_fkey")

    drop_if_exists index(:device_mappings, [:id, :tenant_id])

    drop_if_exists index(:device_mappings, [:tenant_id])

    drop table(:device_mappings)
  end
end
