#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.CreateDeploymentContainerDeployment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deployment_container_deployments, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "deployment_container_deployments_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :deployment_id,
          references(:application_deployments,
            column: :id,
            name: "deployment_container_deployments_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :container_deployment_id,
          references(:container_deployments,
            column: :id,
            name: "deployment_container_deployments_container_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:deployment_container_deployments, [:tenant_id])
  end

  def down do
    drop constraint(
           :deployment_container_deployments,
           "deployment_container_deployments_tenant_id_fkey"
         )

    drop constraint(
           :deployment_container_deployments,
           "deployment_container_deployments_deployment_id_fkey"
         )

    drop constraint(
           :deployment_container_deployments,
           "deployment_container_deployments_container_deployment_id_fkey"
         )

    drop_if_exists index(:deployment_container_deployments, [:tenant_id])

    drop table(:deployment_container_deployments)
  end
end
