#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.MakeContainerResourceLimitsNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:containers) do
      modify :memory_swappiness, :bigint, null: true, default: nil
      modify :memory_swap, :bigint, null: true, default: nil
      modify :memory_reservation, :bigint, null: true, default: nil
      modify :memory, :bigint, null: true, default: nil
      modify :cpu_realtime_runtime, :bigint, null: true, default: nil
      modify :cpu_realtime_period, :bigint, null: true, default: nil
      modify :cpu_quota, :bigint, null: true, default: nil
      modify :cpu_period, :bigint, null: true, default: nil
    end

    execute "UPDATE containers SET cpu_period = NULL WHERE cpu_period = -1"
    execute "UPDATE containers SET cpu_quota = NULL WHERE cpu_quota = -1"
    execute "UPDATE containers SET cpu_realtime_period = NULL WHERE cpu_realtime_period = -1"
    execute "UPDATE containers SET cpu_realtime_runtime = NULL WHERE cpu_realtime_runtime = -1"
    execute "UPDATE containers SET memory = NULL WHERE memory = -1"
    execute "UPDATE containers SET memory_reservation = NULL WHERE memory_reservation = -1"
    execute "UPDATE containers SET memory_swap = NULL WHERE memory_swap = -2"
    execute "UPDATE containers SET memory_swappiness = NULL WHERE memory_swappiness = -1"
  end

  def down do
    execute "UPDATE containers SET cpu_period = -1 WHERE cpu_period IS NULL"
    execute "UPDATE containers SET cpu_quota = -1 WHERE cpu_quota IS NULL"
    execute "UPDATE containers SET cpu_realtime_period = -1 WHERE cpu_realtime_period IS NULL"
    execute "UPDATE containers SET cpu_realtime_runtime = -1 WHERE cpu_realtime_runtime IS NULL"
    execute "UPDATE containers SET memory = -1 WHERE memory IS NULL"
    execute "UPDATE containers SET memory_reservation = -1 WHERE memory_reservation IS NULL"
    execute "UPDATE containers SET memory_swap = -2 WHERE memory_swap IS NULL"
    execute "UPDATE containers SET memory_swappiness = -1 WHERE memory_swappiness IS NULL"

    alter table(:containers) do
      modify :cpu_period, :bigint, null: false, default: -1
      modify :cpu_quota, :bigint, null: false, default: -1
      modify :cpu_realtime_period, :bigint, null: false, default: -1
      modify :cpu_realtime_runtime, :bigint, null: false, default: -1
      modify :memory, :bigint, null: false, default: -1
      modify :memory_reservation, :bigint, null: false, default: -1
      modify :memory_swap, :bigint, null: false, default: -2
      modify :memory_swappiness, :bigint, null: false, default: -1
    end
  end
end
