#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddSystemModelToApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applications) do
      add :system_model_id,
          references(:system_models,
            column: :id,
            name: "applications_system_model_id_fkey",
            type: :integer,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:applications, [:tenant_id, :name],
                     name: "applications_name_index"
                   )

    create unique_index(:applications, [:tenant_id, :name, :system_model_id],
             name: "applications_name_and_system_model_index"
           )
  end

  def down do
    drop_if_exists unique_index(:applications, [:tenant_id, :name, :system_model_id],
                     name: "applications_name_and_system_model_index"
                   )

    drop constraint(:applications, "applications_system_model_id_fkey")

    create unique_index(:applications, [:tenant_id, :name], name: "applications_name_index")

    alter table(:applications) do
      remove :system_model_id
    end
  end
end
