#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.MultipleSystemModelsPerRelease do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:release_system_models, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "release_system_models_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :release_id,
          references(:application_releases,
            column: :id,
            name: "release_system_models_release_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :system_model_id,
          references(:system_models,
            column: :id,
            name: "release_system_models_system_model_id_fkey",
            type: :integer,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:release_system_models, [:tenant_id])

    alter table(:applications) do
      remove :system_model_id
    end

    drop_if_exists unique_index(:applications, [:tenant_id, :name, :system_model_id],
                     name: "applications_name_and_system_model_index"
                   )
  end

  def down do
    create unique_index(:applications, [:tenant_id, :name, :system_model_id],
             name: "applications_name_and_system_model_index"
           )

    alter table(:applications) do
      add :system_model_id,
          references(:system_models,
            column: :id,
            name: "applications_system_model_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    drop constraint(:release_system_models, "release_system_models_tenant_id_fkey")

    drop constraint(:release_system_models, "release_system_models_release_id_fkey")

    drop constraint(:release_system_models, "release_system_models_system_model_id_fkey")

    drop_if_exists index(:release_system_models, [:tenant_id])

    drop table(:release_system_models)
  end
end
