#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddQuotasToCreateContainer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:containers) do
      add :cpu_period, :bigint, null: false, default: -1
      add :cpu_quota, :bigint, null: false, default: -1
      add :cpu_realtime_period, :bigint, null: false, default: -1
      add :cpu_realtime_runtime, :bigint, null: false, default: -1
      add :memory, :bigint, null: false, default: -1
      add :memory_reservation, :bigint, null: false, default: -1
      add :memory_swap, :bigint, null: false, default: -2
      add :memory_swappiness, :bigint, null: false, default: -1
      add :volume_driver, :text, null: false, default: ""
      add :storage_opt, {:array, :text}, null: false, default: []
      add :read_only_rootfs, :boolean, null: false, default: true
      add :tmpfs, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:containers) do
      remove :tmpfs
      remove :read_only_rootfs
      remove :storage_opt
      remove :volume_driver
      remove :memory_swappiness
      remove :memory_swap
      remove :memory_reservation
      remove :memory
      remove :cpu_realtime_runtime
      remove :cpu_realtime_period
      remove :cpu_quota
      remove :cpu_period
    end
  end
end
