#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddFileDeleteRequestsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_delete_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :force, :boolean, default: false
      add :status, :text, default: "pending"
      add :response_code, :bigint
      add :response_messages, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "file_delete_requests_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_download_request_id,
          references(:file_download_requests,
            column: :id,
            name: "file_delete_requests_file_download_request_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:file_download_requests) do
      add :deleted, :boolean, default: false
    end
  end

  def down do
    alter table(:file_download_requests) do
      remove :deleted
    end

    drop constraint(:file_delete_requests, "file_delete_requests_device_id_fkey")

    drop constraint(:file_delete_requests, "file_delete_requests_file_download_request_id_fkey")

    drop table(:file_delete_requests)
  end
end
