#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.CreateDeviceFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_delete_requests) do
      remove :file_download_request_id
      add :device_file_id, :uuid
    end

    create table(:device_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:file_delete_requests) do
      modify :device_file_id,
             references(:device_files,
               column: :id,
               name: "file_delete_requests_device_file_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:device_files) do
      add :file_id, :text, null: false
      add :path_on_device, :text
      add :size_bytes, :bigint
      add :deleted, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "device_files_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "device_files_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_download_request_id,
          references(:file_download_requests,
            column: :id,
            name: "device_files_file_download_request_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:device_files, [:tenant_id])

    create index(:device_files, [:id, :tenant_id], unique: true)

    create unique_index(:device_files, [:tenant_id, :file_id], name: "device_files_file_id_index")

    alter table(:file_download_requests) do
      remove :deleted
      remove :path_on_device
    end
  end

  def down do
    alter table(:file_download_requests) do
      add :path_on_device, :text
      add :deleted, :boolean, default: false
    end

    drop constraint(:device_files, "device_files_tenant_id_fkey")

    drop constraint(:device_files, "device_files_device_id_fkey")

    drop constraint(:device_files, "device_files_file_download_request_id_fkey")

    drop_if_exists unique_index(:device_files, [:tenant_id, :file_id],
                     name: "device_files_file_id_index"
                   )

    drop_if_exists index(:device_files, [:id, :tenant_id])

    drop_if_exists index(:device_files, [:tenant_id])

    alter table(:device_files) do
      remove :file_download_request_id
      remove :device_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :deleted
      remove :size_bytes
      remove :path_on_device
      remove :file_id
    end

    drop constraint(:file_delete_requests, "file_delete_requests_device_file_id_fkey")

    alter table(:file_delete_requests) do
      modify :device_file_id, :uuid
    end

    drop table(:device_files)

    alter table(:file_delete_requests) do
      remove :device_file_id

      add :file_download_request_id,
          references(:file_download_requests,
            column: :id,
            name: "file_delete_requests_file_download_request_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
