#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AutomatedCleanup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Note the tables were deleted in a previous migration, so we don't need to worry about them here.
  # Since ash added deletion snapshots, we can take advantage of that.
  def up do
    drop_if_exists table(:deployment_channels)

    drop_if_exists table(:deployment_target)

    drop_if_exists table(:deployment_targets)

    drop_if_exists table(:update_campaign_targets)

    drop_if_exists table(:update_channels)

    drop_if_exists table(:deployment_campaign)

    drop_if_exists table(:deployment_campaigns)

    drop_if_exists table(:update_campaigns)
  end

  def down do
    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
