#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.RefactorFilesResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:file_download_requests), :progress, to: :progress_tracked

    rename table(:file_download_requests), :status_progress, to: :progress_percentage

    rename table(:file_download_requests), :status_code, to: :response_code

    rename table(:file_download_requests), :message, to: :response_message

    alter table(:file_download_requests) do
      modify :destination_type, :text, null: false, default: nil
      modify :digest, :text, null: false
    end

    alter table(:files) do
      remove :url
      remove :group_id
      remove :user_id
      remove :mode
    end
  end

  def down do
    alter table(:files) do
      add :mode, :bigint, default: 420
      add :user_id, :bigint, default: 0
      add :group_id, :bigint, default: 0
      add :url, :text
    end

    alter table(:file_download_requests) do
      modify :digest, :text, null: true
      modify :destination_type, :text, null: true, default: "storage"
    end

    rename table(:file_download_requests), :response_message, to: :message

    rename table(:file_download_requests), :response_code, to: :status_code

    rename table(:file_download_requests), :progress_percentage, to: :status_progress

    rename table(:file_download_requests), :progress_tracked, to: :progress
  end
end
