#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddFileManagenentMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_delete_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :force, :boolean, default: false
      add :status, :text, default: "pending"
      add :response_code, :bigint
      add :response_messages, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "file_delete_requests_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_download_request_id, :uuid, null: false
    end

    alter table(:campaign_targets) do
      add :file_download_request_id, :uuid
    end

    create table(:file_upload_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :source, :text
      add :source_type, :text, null: false
      add :encoding, :text, default: ""
      add :progress_tracked, :boolean, default: false
      add :status, :text, default: "pending"
      add :progress_percentage, :bigint
      add :response_code, :bigint
      add :response_message, :text
      add :http_headers, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "file_upload_requests_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "file_upload_requests_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:file_upload_requests, [:tenant_id])

    create index(:file_upload_requests, [:id, :tenant_id], unique: true)

    create table(:repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :handle, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "repositories_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:repositories, [:tenant_id])

    create index(:repositories, [:id, :tenant_id], unique: true)

    create unique_index(:repositories, [:tenant_id, :handle], name: "repositories_handle_index")

    create unique_index(:repositories, [:tenant_id, :name], name: "repositories_name_index")

    create table(:file_download_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:file_delete_requests) do
      modify :file_download_request_id,
             references(:file_download_requests,
               column: :id,
               name: "file_delete_requests_file_download_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:campaign_targets) do
      modify :file_download_request_id,
             references(:file_download_requests,
               column: :id,
               name: "campaign_targets_file_download_request_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:file_download_requests) do
      add :url, :text, null: false
      add :file_name, :text
      add :uncompressed_file_size_bytes, :bigint
      add :digest, :text, null: false
      add :encoding, :text, default: ""
      add :ttl_seconds, :bigint, default: 0
      add :file_mode, :bigint, default: 0
      add :user_id, :bigint, default: -1
      add :group_id, :bigint, default: -1
      add :destination_type, :text, null: false
      add :destination, :text
      add :path_on_device, :text
      add :progress_tracked, :boolean, default: false
      add :status, :text, default: "pending"
      add :progress_percentage, :bigint
      add :response_code, :bigint
      add :response_message, :text
      add :is_manual, :boolean
      add :deleted, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "file_download_requests_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "file_download_requests_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:file_download_requests, [:tenant_id])

    create index(:file_download_requests, [:id, :tenant_id], unique: true)

    create table(:files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :size, :bigint, null: false
      add :is_archive, :boolean, null: false
      add :base_file, :map, null: false
      add :gz_file, :map, null: false
      add :lz4_file, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "files_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :repository_id,
          references(:repositories,
            column: :id,
            with: [tenant_id: :tenant_id],
            match: :simple,
            name: "files_repository_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:files, [:tenant_id])

    create index(:files, [:id, :tenant_id], unique: true)

    create unique_index(:files, [:tenant_id, :name, :repository_id],
             name: "files_unique_repository_file_index"
           )
  end

  def down do
    drop constraint(:files, "files_tenant_id_fkey")

    drop constraint(:files, "files_repository_id_fkey")

    drop_if_exists unique_index(:files, [:tenant_id, :name, :repository_id],
                     name: "files_unique_repository_file_index"
                   )

    drop_if_exists index(:files, [:id, :tenant_id])

    drop_if_exists index(:files, [:tenant_id])

    drop table(:files)

    drop constraint(:file_download_requests, "file_download_requests_tenant_id_fkey")

    drop constraint(:file_download_requests, "file_download_requests_device_id_fkey")

    drop_if_exists index(:file_download_requests, [:id, :tenant_id])

    drop_if_exists index(:file_download_requests, [:tenant_id])

    alter table(:file_download_requests) do
      remove :device_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :deleted
      remove :is_manual
      remove :response_message
      remove :response_code
      remove :progress_percentage
      remove :status
      remove :progress_tracked
      remove :path_on_device
      remove :destination
      remove :destination_type
      remove :group_id
      remove :user_id
      remove :file_mode
      remove :ttl_seconds
      remove :encoding
      remove :digest
      remove :uncompressed_file_size_bytes
      remove :file_name
      remove :url
    end

    drop constraint(:campaign_targets, "campaign_targets_file_download_request_id_fkey")

    alter table(:campaign_targets) do
      modify :file_download_request_id, :uuid
    end

    drop constraint(:file_delete_requests, "file_delete_requests_file_download_request_id_fkey")

    alter table(:file_delete_requests) do
      modify :file_download_request_id, :uuid
    end

    drop table(:file_download_requests)

    drop constraint(:repositories, "repositories_tenant_id_fkey")

    drop_if_exists unique_index(:repositories, [:tenant_id, :name],
                     name: "repositories_name_index"
                   )

    drop_if_exists unique_index(:repositories, [:tenant_id, :handle],
                     name: "repositories_handle_index"
                   )

    drop_if_exists index(:repositories, [:id, :tenant_id])

    drop_if_exists index(:repositories, [:tenant_id])

    drop table(:repositories)

    drop constraint(:file_upload_requests, "file_upload_requests_tenant_id_fkey")

    drop constraint(:file_upload_requests, "file_upload_requests_device_id_fkey")

    drop_if_exists index(:file_upload_requests, [:id, :tenant_id])

    drop_if_exists index(:file_upload_requests, [:tenant_id])

    drop table(:file_upload_requests)

    alter table(:campaign_targets) do
      remove :file_download_request_id
    end

    drop constraint(:file_delete_requests, "file_delete_requests_device_id_fkey")

    drop table(:file_delete_requests)
  end
end
