#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddFileMountAndBindPermissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:container_deployment_file_binds) do
      add :file_mode, :bigint
      add :user_id, :bigint
      add :group_id, :bigint
    end

    alter table(:container_file_mounts) do
      add :file_mode, :bigint
      add :user_id, :bigint
      add :group_id, :bigint
    end
  end

  def down do
    alter table(:container_file_mounts) do
      remove :group_id
      remove :user_id
      remove :file_mode
    end

    alter table(:container_deployment_file_binds) do
      remove :group_id
      remove :user_id
      remove :file_mode
    end
  end
end
