#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.CreateFilesResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :handle, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "repositories_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:repositories, [:tenant_id])

    create index(:repositories, [:id, :tenant_id], unique: true)

    create unique_index(:repositories, [:tenant_id, :handle], name: "repositories_handle_index")

    create unique_index(:repositories, [:tenant_id, :name], name: "repositories_name_index")

    alter table(:files) do
      modify :group_id, :bigint, default: 0
      modify :user_id, :bigint, default: 0
      modify :mode, :bigint, default: 420

      add :repository_id,
          references(:repositories,
            column: :id,
            with: [tenant_id: :tenant_id],
            match: :simple,
            name: "files_repository_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:files, "files_repository_id_fkey")

    alter table(:files) do
      remove :repository_id
      modify :mode, :bigint, default: nil
      modify :user_id, :bigint, default: nil
      modify :group_id, :bigint, default: nil
    end

    drop_if_exists unique_index(:repositories, [:tenant_id, :name],
                     name: "repositories_name_index"
                   )

    drop_if_exists unique_index(:repositories, [:tenant_id, :handle],
                     name: "repositories_handle_index"
                   )

    drop constraint(:repositories, "repositories_tenant_id_fkey")

    drop_if_exists index(:repositories, [:id, :tenant_id])

    drop_if_exists index(:repositories, [:tenant_id])

    drop table(:repositories)
  end
end
