# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

defmodule Edgehog.Repo.Migrations.ExpandContainerFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:containers) do
      add :domainname, :text
      add :user, :text
      add :command, {:array, :text}
      add :healthcheck_test, {:array, :text}
      add :healthcheck_interval, :bigint
      add :healthcheck_timeout, :bigint
      add :healthcheck_retries, :bigint
      add :healthcheck_start_period, :bigint
      add :healthcheck_start_interval, :bigint
      add :working_directory, :text
      add :entrypoint, {:array, :text}
      add :network_disabled, :boolean
      add :label_keys, {:array, :text}
      add :label_values, {:array, :text}
      add :stop_signal, :text
      add :stop_timeout, :bigint, default: 10
      add :restart_policy_maximum_retry_count, :bigint
      add :exposed_ports, {:array, :text}
      add :cpu_shares, :bigint
      add :cpuset_cpus, :text
      add :device_cgroup_rules, {:array, :text}
      add :ulimits_name, {:array, :text}
      add :ulimits_soft, {:array, :bigint}
      add :ulimits_hard, {:array, :bigint}
      add :auto_remove, :boolean
      add :storage_opt_keys, {:array, :text}
      add :storage_opt_values, {:array, :text}
      add :tmpfs_paths, {:array, :text}
      add :tmpfs_options, {:array, :text}
      add :cgroups_mode, :text
      add :dns, {:array, :text}
      add :dns_options, {:array, :text}
      add :dns_search, {:array, :text}
      add :group_add, {:array, :text}
      add :ipc_mode, :text
      add :oom_score_adjustment, :bigint
      add :userns_mode, :text
      add :sysctls_keys, {:array, :text}
      add :sysctls_values, {:array, :text}
      add :shm_size, :bigint
      add :runtime, :text
      add :log_type, :text
      add :log_config_keys, {:array, :text}
      add :log_config_values, {:array, :text}
      add :blkio_weight, :bigint
      add :blkio_weight_device_path, {:array, :text}
      add :blkio_weight_device_weight, {:array, :bigint}
      add :blkio_device_read_bps_path, {:array, :text}
      add :blkio_device_read_bps_rate, {:array, :bigint}
      add :blkio_device_write_bps_path, {:array, :text}
      add :blkio_device_write_bps_rate, {:array, :bigint}
      add :blkio_device_read_iops_path, {:array, :text}
      add :blkio_device_read_iops_rate, {:array, :bigint}
      add :blkio_device_write_iops_path, {:array, :text}
      add :blkio_device_write_iops_rate, {:array, :bigint}
      add :securityopt, {:array, :text}
      add :pid_mode, :text
      add :masked_paths, {:array, :text}
      add :readonly_paths, {:array, :text}
      remove :storage_opt
      remove :tmpfs
    end
  end

  def down do
    alter table(:containers) do
      add :tmpfs, {:array, :text}, null: false, default: []
      add :storage_opt, {:array, :text}, null: false, default: []
      remove :readonly_paths
      remove :masked_paths
      remove :pid_mode
      remove :securityopt
      remove :blkio_device_write_iops_rate
      remove :blkio_device_write_iops_path
      remove :blkio_device_read_iops_rate
      remove :blkio_device_read_iops_path
      remove :blkio_device_write_bps_rate
      remove :blkio_device_write_bps_path
      remove :blkio_device_read_bps_rate
      remove :blkio_device_read_bps_path
      remove :blkio_weight_device_weight
      remove :blkio_weight_device_path
      remove :blkio_weight
      remove :log_config_values
      remove :log_config_keys
      remove :log_type
      remove :runtime
      remove :shm_size
      remove :sysctls_values
      remove :sysctls_keys
      remove :userns_mode
      remove :oom_score_adjustment
      remove :ipc_mode
      remove :group_add
      remove :dns_search
      remove :dns_options
      remove :dns
      remove :cgroups_mode
      remove :tmpfs_options
      remove :tmpfs_paths
      remove :storage_opt_values
      remove :storage_opt_keys
      remove :auto_remove
      remove :ulimits_hard
      remove :ulimits_soft
      remove :ulimits_name
      remove :device_cgroup_rules
      remove :cpuset_cpus
      remove :cpu_shares
      remove :exposed_ports
      remove :restart_policy_maximum_retry_count
      remove :stop_timeout
      remove :stop_signal
      remove :label_values
      remove :label_keys
      remove :network_disabled
      remove :entrypoint
      remove :working_directory
      remove :healthcheck_start_interval
      remove :healthcheck_start_period
      remove :healthcheck_retries
      remove :healthcheck_timeout
      remove :healthcheck_interval
      remove :healthcheck_test
      remove :command
      remove :user
      remove :domainname
    end
  end
end
