#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddUniqueFileDownloadRequestName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Deduplicate existing campaigns before enforcing the unique constraint.
    # Appends a formatted inserted_at timestamp (YYYYMMDD_HH24MISS) to duplicates.
    execute("""
    UPDATE campaigns
    SET name = name || '-' || TO_CHAR(inserted_at, 'YYYYMMDD_HH24MISS')
    WHERE id IN (
      SELECT id
      FROM (
        SELECT id, row_number() OVER(PARTITION BY tenant_id, name ORDER BY inserted_at ASC) as rn
        FROM campaigns
      ) as duplicates
      WHERE duplicates.rn > 1
    )
    """)

    create unique_index(:campaigns, [:tenant_id, :name], name: "campaigns_name_index")

    # Add the column allowing nulls initially
    alter table(:file_download_requests) do
      add :request_name, :text
    end

    # Flush the transaction so the column exists before we try to write to it
    flush()

    # Backfill existing data.
    execute("""
    UPDATE file_download_requests
    SET request_name = file_name
    """)

    # Enforce the NOT NULL constraint
    alter table(:file_download_requests) do
      modify :request_name, :text, null: false
    end

    drop_if_exists unique_index(:file_download_requests, [:tenant_id, :file_name, :device_id],
                     name: "file_download_requests_file_name_index"
                   )

    create unique_index(:file_download_requests, [:tenant_id, :request_name, :device_id],
             name: "file_download_requests_request_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:file_download_requests, [:tenant_id, :request_name, :device_id],
                     name: "file_download_requests_request_name_index"
                   )

    create unique_index(:file_download_requests, [:tenant_id, :file_name, :device_id],
             name: "file_download_requests_file_name_index"
           )

    alter table(:file_download_requests) do
      remove :request_name
    end

    drop_if_exists unique_index(:campaigns, [:tenant_id, :name], name: "campaigns_name_index")
  end
end
