#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.CreateFileDownloadRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_download_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :file_name, :text
      add :uncompressed_file_size_bytes, :bigint
      add :digest, :text
      add :compression, :text, default: ""
      add :ttl_seconds, :bigint, default: 0
      add :file_mode, :bigint, default: 0
      add :user_id, :bigint, default: -1
      add :group_id, :bigint, default: -1
      add :destination, :text, default: "storage"
      add :progress, :boolean, default: false
      add :status, :text
      add :status_progress, :bigint
      add :status_code, :bigint
      add :message, :text
      add :is_manual, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "file_download_requests_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "file_download_requests_device_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:file_download_requests, [:tenant_id])

    create index(:file_download_requests, [:id, :tenant_id], unique: true)

    alter table(:files) do
      modify :repository_id, :uuid, null: false
    end
  end

  def down do
    alter table(:files) do
      modify :repository_id, :uuid, null: true
    end

    drop constraint(:file_download_requests, "file_download_requests_tenant_id_fkey")

    drop constraint(:file_download_requests, "file_download_requests_device_id_fkey")

    drop_if_exists index(:file_download_requests, [:id, :tenant_id])

    drop_if_exists index(:file_download_requests, [:tenant_id])

    drop table(:file_download_requests)
  end
end
