#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

defmodule Edgehog.Repo.Migrations.AddEnvFileBinds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:container_deployment_env_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :file_name, :text
      add :uncompressed_file_size_bytes, :bigint
      add :digest, :text
      add :encoding, :text
      add :uploaded, :boolean, null: false, default: false
      add :state, :text, null: false, default: "created"
      add :last_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "container_deployment_env_files_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :container_deployment_id,
          references(:container_deployments,
            column: :id,
            name: "container_deployment_env_files_container_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "container_deployment_env_files_device_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :file_download_request_id,
          references(:file_download_requests,
            column: :id,
            name: "container_deployment_env_files_file_download_request_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :device_file_id,
          references(:device_files,
            column: :id,
            name: "container_deployment_env_files_device_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:container_deployment_env_files, [:id, :tenant_id], unique: true)

    create index(:container_deployment_env_files, [:tenant_id])

    alter table(:container_deployment_file_binds) do
      modify :file_mount_id, :uuid, null: false
    end

    drop_if_exists index(
                     :container_deployment_file_binds,
                     [:tenant_id, :container_deployment_id, :file_mount_id],
                     name: "file_binds_unique_mount_idx"
                   )
  end

  def down do
    create index(
             :container_deployment_file_binds,
             [:tenant_id, :container_deployment_id, :file_mount_id],
             name: "file_binds_unique_mount_idx",
             unique: true
           )

    alter table(:container_deployment_file_binds) do
      modify :file_mount_id, :uuid, null: true
    end

    drop_if_exists index(:container_deployment_env_files, [:tenant_id])

    drop_if_exists index(:container_deployment_env_files, [:id, :tenant_id])

    drop constraint(
           :container_deployment_env_files,
           "container_deployment_env_files_device_file_id_fkey"
         )

    drop constraint(
           :container_deployment_env_files,
           "container_deployment_env_files_file_download_request_id_fkey"
         )

    drop constraint(
           :container_deployment_env_files,
           "container_deployment_env_files_device_id_fkey"
         )

    drop constraint(
           :container_deployment_env_files,
           "container_deployment_env_files_container_deployment_id_fkey"
         )

    drop constraint(
           :container_deployment_env_files,
           "container_deployment_env_files_tenant_id_fkey"
         )

    drop table(:container_deployment_env_files)
  end
end
