defmodule Edgehog.Repo.Migrations.AddUniqueIndexToFileBinds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:container_deployment_file_binds,
             [:container_deployment_id, :file_mount_id],
             name: "file_binds_unique_mount_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:container_deployment_file_binds,
                     [:container_deployment_id, :file_mount_id],
                     name: "file_binds_unique_mount_idx"
                   )
  end
end
