defmodule Edgehog.Repo.Migrations.AddFileBindStateAndDevice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:container_deployment_file_binds) do
      add :state, :text, null: false, default: "created"
      add :last_message, :text

      add :device_id,
          references(:devices,
            column: :id,
            name: "container_deployment_file_binds_device_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    execute """
    UPDATE container_deployment_file_binds AS file_bind
    SET device_id = container_deployment.device_id
    FROM container_deployments AS container_deployment
    WHERE container_deployment.id = file_bind.container_deployment_id
    """

    alter table(:container_deployment_file_binds) do
      modify :device_id, :bigint, null: false
    end
  end

  def down do
    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_device_id_fkey"
         )

    alter table(:container_deployment_file_binds) do
      remove :device_id
      remove :last_message
      remove :state
    end
  end
end
