#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddContainerDeploymentEnvAndFileMounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:container_deployments) do
      add :env, {:array, :map}, null: false, default: []
      add :env_strategy, :text, null: false, default: "merge"
    end

    create table(:container_deployment_file_binds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "container_deployment_file_binds_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :container_deployment_id,
          references(:container_deployments,
            column: :id,
            name: "container_deployment_file_binds_container_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :file_mount_id, :uuid

      add :file_download_request_id,
          references(:file_download_requests,
            column: :id,
            name: "container_deployment_file_binds_file_download_request_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :device_file_id,
          references(:device_files,
            column: :id,
            name: "container_deployment_file_binds_device_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:container_deployment_file_binds, [:id, :tenant_id], unique: true)

    create index(:container_deployment_file_binds, [:tenant_id])

    create table(:container_file_mounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:container_deployment_file_binds) do
      modify :file_mount_id,
             references(:container_file_mounts,
               column: :id,
               name: "container_deployment_file_binds_file_mount_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:container_file_mounts) do
      add :mountpoint, :text, null: false
      add :required, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "container_file_mounts_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :container_id,
          references(:containers,
            column: :id,
            name: "container_file_mounts_container_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:container_file_mounts, [:tenant_id, :container_id, :mountpoint],
             name: "container_file_mounts_container_mountpoint_index"
           )

    alter table(:container_file_mounts) do
      add :default_file_id,
          references(:files,
            column: :id,
            name: "container_file_mounts_default_file_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:container_file_mounts, [:id, :tenant_id], unique: true)

    create index(:container_file_mounts, [:tenant_id])
  end

  def down do
    drop_if_exists index(:container_file_mounts, [:tenant_id])

    drop_if_exists index(:container_file_mounts, [:id, :tenant_id])

    drop constraint(:container_file_mounts, "container_file_mounts_default_file_id_fkey")

    drop constraint(:container_file_mounts, "container_file_mounts_container_id_fkey")

    drop constraint(:container_file_mounts, "container_file_mounts_tenant_id_fkey")

    alter table(:container_file_mounts) do
      remove :default_file_id
    end

    drop_if_exists unique_index(:container_file_mounts, [:tenant_id, :container_id, :mountpoint],
                     name: "container_file_mounts_container_mountpoint_index"
                   )

    alter table(:container_file_mounts) do
      remove :container_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :required
      remove :mountpoint
    end

    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_device_file_id_fkey"
         )

    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_file_download_request_id_fkey"
         )

    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_file_mount_id_fkey"
         )

    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_container_deployment_id_fkey"
         )

    drop constraint(
           :container_deployment_file_binds,
           "container_deployment_file_binds_tenant_id_fkey"
         )

    alter table(:container_deployment_file_binds) do
      modify :file_mount_id, :uuid
    end

    drop table(:container_file_mounts)

    drop_if_exists index(:container_deployment_file_binds, [:tenant_id])

    drop_if_exists index(:container_deployment_file_binds, [:id, :tenant_id])

    drop table(:container_deployment_file_binds)

    alter table(:container_deployments) do
      remove :env_strategy
      remove :env
    end
  end
end
