#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddDeviceRequestsToContainers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:container_deployment_device_request_deployments, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "container_deployment_device_request_deployments_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :container_deployment_id,
          references(:container_deployments,
            column: :id,
            name: "container_deployment_device_request_deployments_container_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :device_request_deployment_id, :uuid, null: false, primary_key: true
    end

    create index(:container_deployment_device_request_deployments, [:tenant_id])

    create table(:device_request_deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:container_deployment_device_request_deployments) do
      modify :device_request_deployment_id,
             references(:device_request_deployments,
               column: :id,
               name:
                 "container_deployment_device_request_deployments_device_request_deployment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:device_request_deployments) do
      add :last_message, :text
      add :state, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "device_request_deployments_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :device_request_id, :uuid
      add :device_id, :bigint
    end

    create index(:device_request_deployments, [:tenant_id])

    create index(:device_request_deployments, [:id, :tenant_id], unique: true)

    create unique_index(:device_request_deployments, [:tenant_id, :device_request_id, :device_id],
             name: "device_request_deployments_device_request_instance_index"
           )

    create table(:device_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:device_request_deployments) do
      modify :device_request_id,
             references(:device_requests,
               column: :id,
               name: "device_request_deployments_device_request_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :device_id,
             references(:devices,
               column: :id,
               name: "device_request_deployments_device_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:device_requests) do
      add :driver, :text, default: ""
      add :count, :bigint, default: -1
      add :device_ids, {:array, :text}, default: []
      add :db_capabilities, {:array, :text}, default: []
      add :options, :map, default: %{}

      add :tenant_id,
          references(:tenants,
            column: :tenant_id,
            name: "device_requests_tenant_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :container_id,
          references(:containers,
            column: :id,
            name: "device_requests_container_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:device_requests, [:tenant_id])

    create index(:device_requests, [:id, :tenant_id], unique: true)
  end

  def down do
    drop constraint(:device_requests, "device_requests_tenant_id_fkey")

    drop constraint(:device_requests, "device_requests_container_id_fkey")

    drop_if_exists index(:device_requests, [:id, :tenant_id])

    drop_if_exists index(:device_requests, [:tenant_id])

    alter table(:device_requests) do
      remove :container_id
      remove :tenant_id
      remove :options
      remove :db_capabilities
      remove :device_ids
      remove :count
      remove :driver
    end

    drop constraint(
           :device_request_deployments,
           "device_request_deployments_device_request_id_fkey"
         )

    drop constraint(:device_request_deployments, "device_request_deployments_device_id_fkey")

    alter table(:device_request_deployments) do
      modify :device_id, :bigint
      modify :device_request_id, :uuid
    end

    drop table(:device_requests)

    drop constraint(:device_request_deployments, "device_request_deployments_tenant_id_fkey")

    drop_if_exists unique_index(
                     :device_request_deployments,
                     [:tenant_id, :device_request_id, :device_id],
                     name: "device_request_deployments_device_request_instance_index"
                   )

    drop_if_exists index(:device_request_deployments, [:id, :tenant_id])

    drop_if_exists index(:device_request_deployments, [:tenant_id])

    alter table(:device_request_deployments) do
      remove :device_id
      remove :device_request_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :state
      remove :last_message
    end

    drop constraint(
           :container_deployment_device_request_deployments,
           "container_deployment_device_request_deployments_device_request_deployment_id_fkey"
         )

    alter table(:container_deployment_device_request_deployments) do
      modify :device_request_deployment_id, :uuid
    end

    drop table(:device_request_deployments)

    drop constraint(
           :container_deployment_device_request_deployments,
           "container_deployment_device_request_deployments_tenant_id_fkey"
         )

    drop constraint(
           :container_deployment_device_request_deployments,
           "container_deployment_device_request_deployments_container_deployment_id_fkey"
         )

    drop_if_exists index(:container_deployment_device_request_deployments, [:tenant_id])

    drop table(:container_deployment_device_request_deployments)
  end
end
