defmodule Edgehog.Repo.Migrations.AddFileBindUploadFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:container_deployment_file_binds) do
      add :file_name, :text
      add :uncompressed_file_size_bytes, :bigint
      add :digest, :text
      add :encoding, :text, default: ""
      add :uploaded, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:container_deployment_file_binds) do
      remove :uploaded
      remove :encoding
      remove :digest
      remove :uncompressed_file_size_bytes
      remove :file_name
    end
  end
end
