# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

defmodule Edgehog.Repo.Migrations.ExpandContainerFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  but modified to migrate `storage_opts` and `tmpfs`.
  """

  use Ecto.Migration
  import Ecto.Query

  alias Edgehog.Repo

  def up do
    alter table(:containers) do
      add :domainname, :text
      add :user, :text
      add :command, {:array, :text}
      add :healthcheck_test, {:array, :text}
      add :healthcheck_interval, :bigint
      add :healthcheck_timeout, :bigint
      add :healthcheck_retries, :bigint
      add :healthcheck_start_period, :bigint
      add :healthcheck_start_interval, :bigint
      add :working_directory, :text
      add :entrypoint, {:array, :text}
      add :network_disabled, :boolean
      add :label_keys, {:array, :text}
      add :label_values, {:array, :text}
      add :stop_signal, :text
      add :stop_timeout, :bigint, default: 10
      add :restart_policy_maximum_retry_count, :bigint
      add :exposed_ports, {:array, :text}
      add :cpu_shares, :bigint
      add :cpuset_cpus, :text
      add :device_cgroup_rules, {:array, :text}
      add :ulimits_name, {:array, :text}
      add :ulimits_soft, {:array, :bigint}
      add :ulimits_hard, {:array, :bigint}
      add :auto_remove, :boolean
      add :storage_opt_keys, {:array, :text}
      add :storage_opt_values, {:array, :text}
      add :tmpfs_paths, {:array, :text}
      add :tmpfs_options, {:array, :text}
      add :cgroups_mode, :text
      add :dns, {:array, :text}
      add :dns_options, {:array, :text}
      add :dns_search, {:array, :text}
      add :group_add, {:array, :text}
      add :ipc_mode, :text
      add :oom_score_adjustment, :bigint
      add :userns_mode, :text
      add :sysctls_keys, {:array, :text}
      add :sysctls_values, {:array, :text}
      add :shm_size, :bigint
      add :runtime, :text
      add :log_type, :text
      add :log_config_keys, {:array, :text}
      add :log_config_values, {:array, :text}
      add :blkio_weight, :bigint
      add :blkio_weight_device_path, {:array, :text}
      add :blkio_weight_device_weight, {:array, :bigint}
      add :blkio_device_read_bps_path, {:array, :text}
      add :blkio_device_read_bps_rate, {:array, :bigint}
      add :blkio_device_write_bps_path, {:array, :text}
      add :blkio_device_write_bps_rate, {:array, :bigint}
      add :blkio_device_read_iops_path, {:array, :text}
      add :blkio_device_read_iops_rate, {:array, :bigint}
      add :blkio_device_write_iops_path, {:array, :text}
      add :blkio_device_write_iops_rate, {:array, :bigint}
      add :securityopt, {:array, :text}
      add :pid_mode, :text
      add :masked_paths, {:array, :text}
      add :readonly_paths, {:array, :text}
    end

    flush()

    from(c in "containers", select: %{id: c.id, storage_opt: c.storage_opt, tmpfs: c.tmpfs})
    |> Repo.all(skip_tenant_id: true, schema_migration: true)
    |> Enum.each(fn container ->
      {storage_opt_keys, storage_opt_values} = split_key_value_pairs(container.storage_opt)
      {tmpfs_paths, tmpfs_options} = split_key_value_pairs(container.tmpfs)

      from(c in "containers", where: c.id == ^container.id)
      |> Repo.update_all(
        [
          set: [
            storage_opt_keys: storage_opt_keys,
            storage_opt_values: storage_opt_values,
            tmpfs_paths: tmpfs_paths,
            tmpfs_options: tmpfs_options
          ]
        ],
        skip_tenant_id: true,
        schema_migration: true
      )
    end)

    alter table(:containers) do
      remove :storage_opt
      remove :tmpfs
    end
  end

  def down do
    alter table(:containers) do
      add :tmpfs, {:array, :text}, null: false, default: []
      add :storage_opt, {:array, :text}, null: false, default: []
    end

    flush()

    from(c in "containers",
      select: %{
        id: c.id,
        storage_opt_keys: c.storage_opt_keys,
        storage_opt_values: c.storage_opt_values,
        tmpfs_paths: c.tmpfs_paths,
        tmpfs_options: c.tmpfs_options
      }
    )
    |> Repo.all(skip_tenant_id: true, schema_migration: true)
    |> Enum.each(fn container ->
      storage_opt =
        join_key_value_pairs(
          container.storage_opt_keys,
          container.storage_opt_values,
          :storage_opts
        )

      tmpfs = join_key_value_pairs(container.tmpfs_paths, container.tmpfs_options, :tmpfs)

      from(c in "containers", where: c.id == ^container.id)
      |> Repo.update_all(
        [
          set: [
            storage_opt: storage_opt,
            tmpfs: tmpfs
          ]
        ],
        skip_tenant_id: true,
        schema_migration: true
      )
    end)

    alter table(:containers) do
      remove :readonly_paths
      remove :masked_paths
      remove :pid_mode
      remove :securityopt
      remove :blkio_device_write_iops_rate
      remove :blkio_device_write_iops_path
      remove :blkio_device_read_iops_rate
      remove :blkio_device_read_iops_path
      remove :blkio_device_write_bps_rate
      remove :blkio_device_write_bps_path
      remove :blkio_device_read_bps_rate
      remove :blkio_device_read_bps_path
      remove :blkio_weight_device_weight
      remove :blkio_weight_device_path
      remove :blkio_weight
      remove :log_config_values
      remove :log_config_keys
      remove :log_type
      remove :runtime
      remove :shm_size
      remove :sysctls_values
      remove :sysctls_keys
      remove :userns_mode
      remove :oom_score_adjustment
      remove :ipc_mode
      remove :group_add
      remove :dns_search
      remove :dns_options
      remove :dns
      remove :cgroups_mode
      remove :tmpfs_options
      remove :tmpfs_paths
      remove :storage_opt_values
      remove :storage_opt_keys
      remove :auto_remove
      remove :ulimits_hard
      remove :ulimits_soft
      remove :ulimits_name
      remove :device_cgroup_rules
      remove :cpuset_cpus
      remove :cpu_shares
      remove :exposed_ports
      remove :restart_policy_maximum_retry_count
      remove :stop_timeout
      remove :stop_signal
      remove :label_values
      remove :label_keys
      remove :network_disabled
      remove :entrypoint
      remove :working_directory
      remove :healthcheck_start_interval
      remove :healthcheck_start_period
      remove :healthcheck_retries
      remove :healthcheck_timeout
      remove :healthcheck_interval
      remove :healthcheck_test
      remove :command
      remove :user
      remove :domainname
    end
  end

  defp split_key_value_pairs(nil), do: {nil, nil}

  defp split_key_value_pairs(items) do
    items
    |> Enum.map(fn item ->
      case String.split(item, "=", parts: 2) do
        [key, value] -> {key, value}
        [key] -> {key, ""}
      end
    end)
    |> Enum.unzip()
  end

  defp join_key_value_pairs(keys, values, column) do
    keys = keys || []
    values = values || []

    if length(keys) != length(values) do
      raise """
      Cannot translate containers: got #{length(keys)} keys and #{length(values)} values on column #{inspect(column)}.

      Keys: #{inspect(keys)}
      Values: #{inspect(values)}
      """
    end

    key_values = Enum.zip(keys, values)

    Enum.map(key_values, fn
      {key, nil} -> key
      {key, value} -> "#{key}=#{value}"
    end)
  end
end
