#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Ash.Astarte.Triggers.HandlerBehavior do
  @moduledoc """
  Behavior for a trigger handler. A trigger resource should define a module
  that specifies this behavior, which will allow the extension to correctly
  handle the trigger.

  The callback expects as first argument the resource generated by the trigger
  query by astarte. the second argument is a context, carrying eventual
  information, such as the tenant, the realm_id, the device_id and the
  timestamp of the trigger.
  """

  @type context() :: map()
  @type event() :: map()

  @doc """
  Handle event callback.

  The event is one of the triggers defined in the `triggers` section of the
  triggers domain

  opts are currently not dispatched. they'll always be an empty list []

  the context is a map containing the following information on the connection:
  - tenant    :: the tenant for which the request was made
  - realm_id  :: the realm id of the device
  - device_id :: the astarte device id
  - timestamp :: the timestamp of the trigger
  """
  @callback handle_event(
              event :: event(),
              opts :: Keyword.t(),
              context :: context()
            ) ::
              {:ok, term()} | :ok | {:error, term()}
end
