#
# This file is part of Edgehog.
#
# Copyright 2024 - 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Astarte.Device.CreateContainerRequest.RequestData do
  @moduledoc false

  defstruct [
    :id,
    :deploymentId,
    :imageId,
    :networkIds,
    :volumeIds,
    :deviceMappingIds,
    :deviceRequestIds,
    :hostname,
    :domainname,
    :user,
    :cmd,
    :healthcheckTest,
    :healthcheckInterval,
    :healthcheckTimeout,
    :healthcheckRetries,
    :healthcheckStartPeriod,
    :healthcheckStartInterval,
    :workingDir,
    :entrypoint,
    :networkDisabled,
    :labelsKeys,
    :labelsValues,
    :stopSignal,
    :stopTimeout,
    :restartPolicy,
    :restartPolicyMaximumRetryCount,
    :env,
    :binds,
    :networkMode,
    :portBindings,
    :exposedPorts,
    :extraHosts,
    :capAdd,
    :capDrop,
    :cpuShares,
    :cpusetCpus,
    :cpuPeriod,
    :cpuQuota,
    :cpuRealtimePeriod,
    :cpuRealtimeRuntime,
    :memory,
    :memoryReservation,
    :memorySwap,
    :memorySwappiness,
    :deviceCgroupRules,
    :ulimitsName,
    :ulimitsSoft,
    :ulimitsHard,
    :autoRemove,
    :volumeDriver,
    :storageOptKeys,
    :storageOptValues,
    :readOnlyRootfs,
    :tmpfsPaths,
    :tmpfsOptions,
    :cgroupnsMode,
    :dns,
    :dnsOptions,
    :dnsSearch,
    :groupAdd,
    :ipcMode,
    :oomScoreAdj,
    :usernsMode,
    :sysctlsKeys,
    :sysctlsValues,
    :shmSize,
    :runtime,
    :privileged,
    :logType,
    :logConfigKeys,
    :logConfigValues,
    :blkioWeight,
    :blkioWeightDevicePath,
    :blkioWeightDeviceWeight,
    :blkioDeviceReadBpsPath,
    :blkioDeviceReadBpsRate,
    :blkioDeviceWriteBpsPath,
    :blkioDeviceWriteBpsRate,
    :blkioDeviceReadIopsPath,
    :blkioDeviceReadIopsRate,
    :blkioDeviceWriteIopsPath,
    :blkioDeviceWriteIopsRate,
    :securityopt,
    :pidMode,
    :maskedPaths,
    :readonlyPaths
  ]

  @type t() :: %__MODULE__{
          id: String.t(),
          deploymentId: String.t(),
          imageId: String.t(),
          networkIds: list(String.t()),
          volumeIds: list(String.t()),
          deviceMappingIds: list(String.t()),
          deviceRequestIds: list(String.t()),
          hostname: String.t(),
          domainname: String.t(),
          user: String.t(),
          cmd: list(String.t()),
          healthcheckTest: list(String.t()),
          healthcheckInterval: integer(),
          healthcheckTimeout: integer(),
          healthcheckRetries: integer(),
          healthcheckStartPeriod: integer(),
          healthcheckStartInterval: integer(),
          workingDir: String.t(),
          entrypoint: list(String.t()),
          networkDisabled: boolean(),
          labelsKeys: list(String.t()),
          labelsValues: list(String.t()),
          stopSignal: String.t(),
          stopTimeout: integer(),
          restartPolicy: String.t(),
          restartPolicyMaximumRetryCount: integer(),
          env: list(tuple()),
          binds: list(String.t()),
          networkMode: String.t(),
          portBindings: list(String.t()),
          exposedPorts: list(String.t()),
          extraHosts: list(String.t()),
          capAdd: list(String.t()),
          capDrop: list(String.t()),
          cpuShares: integer(),
          cpusetCpus: String.t(),
          cpuPeriod: integer(),
          cpuQuota: integer(),
          cpuRealtimePeriod: integer(),
          cpuRealtimeRuntime: integer(),
          memory: integer(),
          memoryReservation: integer(),
          memorySwap: integer(),
          memorySwappiness: integer(),
          deviceCgroupRules: list(String.t()),
          ulimitsName: list(String.t()),
          ulimitsSoft: list(integer()),
          ulimitsHard: list(integer()),
          autoRemove: boolean(),
          volumeDriver: String.t(),
          storageOptKeys: list(String.t()),
          storageOptValues: list(String.t()),
          readOnlyRootfs: boolean(),
          tmpfsPaths: list(String.t()),
          tmpfsOptions: list(String.t()),
          cgroupnsMode: String.t(),
          dns: list(String.t()),
          dnsOptions: list(String.t()),
          dnsSearch: list(String.t()),
          groupAdd: list(String.t()),
          ipcMode: String.t(),
          oomScoreAdj: integer(),
          usernsMode: String.t(),
          sysctlsKeys: list(String.t()),
          sysctlsValues: list(String.t()),
          shmSize: integer(),
          runtime: String.t(),
          privileged: String.t(),
          logType: String.t(),
          logConfigKeys: list(String.t()),
          logConfigValues: list(String.t()),
          blkioWeight: integer(),
          blkioWeightDevicePath: list(String.t()),
          blkioWeightDeviceWeight: list(integer()),
          blkioDeviceReadBpsPath: list(String.t()),
          blkioDeviceReadBpsRate: list(integer()),
          blkioDeviceWriteBpsPath: list(String.t()),
          blkioDeviceWriteBpsRate: list(integer()),
          blkioDeviceReadIopsPath: list(String.t()),
          blkioDeviceReadIopsRate: list(integer()),
          blkioDeviceWriteIopsPath: list(String.t()),
          blkioDeviceWriteIopsRate: list(integer()),
          securityopt: list(String.t()),
          pidMode: String.t(),
          maskedPaths: list(String.t()),
          readonlyPaths: list(String.t())
        }
end
