# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: backend openfga integration test
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  integration-openfga:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      openfga:
        image: openfga/openfga:v1.16.0
        command: run
        ports:
          - 8080:8080
          - 8081:8081
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: recursive

      - name: Optimize Cache
        uses: ./.github/actions/restore-cache-mtimes

      - name: "Setup jq"
        uses: dcarbone/install-jq-action@b7ef57d46ece78760b4019dbc4080a1ba2a40b45 # v3
      - name: Install OpenFGA cli
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: openfga/cli
          cache: enable
      - name: Setup OpenFGA store
        id: store
        run: |
          fga store create --model ./fga/openfga/fga.mod --format modular > store_response.json
          cat store_response.json
          store_id=$(jq -r '.store.id' store_response.json)
          auth_model_id=$(jq -r '.model.authorization_model_id' store_response.json)
          echo "store_id=$store_id" >> $GITHUB_OUTPUT
          echo "auth_model_id=$auth_model_id" >> $GITHUB_OUTPUT
      - uses: team-alembic/staple-actions/actions/mix-task@8b0f5a1a7cadfbc86c2d00343d4a06a45352ef13 # main
        with:
          mix-env: test
          working-directory: backend
          task: test --only integration_openfga
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          EDGEHOG_AUTHZ_PROVIDER: openfga
          EDGEHOG_OPENFGA_GRPC_ENDPOINT: "localhost:8081"
          EDGEHOG_OPENFGA_STORE_ID: ${{ steps.store.outputs.store_id }}
          EDGEHOG_OPENFGA_AUTH_MODEL_ID: ${{ steps.store.outputs.auth_model_id }}
